name: Next.js CI

on:
  push:
    branches:
      - main # Executa o workflow ao fazer push para a branch "main".
  pull_request:
    branches:
      - main # Executa o workflow para pull requests na branch "main".

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Faz o checkout do repositório.

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Altere para a versão compatível com o seu projeto Next.js.

      - name: Install dependencies
        run: npm install # Instala as dependências.

      - name: Run build
        run: npm run build # Gera o build do Next.js.

      - name: Run tests
        run: npm test -- --watchAll=false # Executa os testes (se houver).

      - name: Export static files (opcional, para SSG)
        run: npm run export
